/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrderDetails {
  id: string;
  status: string;
  intent: string;
  paymentSource: PaymentSource;
  purchaseUnits: PurchaseUnit[];
  payer: Payer;
  createTime: string;
  links: Link[];
}
export interface PaymentSource {
  paypal: Paypal;
}
export interface Paypal {
  name: Name;
  emailAddress?: string | null;
  accountId?: string | null;
  accountStatus?: string | null;
  address?: Address | null;
}
export interface Name {
  givenName?: string | null;
  surname?: string | null;
}
export interface Address {
  addressLine1?: string | null;
  addressLine2?: string | null;
  adminArea2?: string | null;
  adminArea1?: string | null;
  postalCode?: string | null;
  countryCode?: string | null;
}
export interface PurchaseUnit {
  referenceId?: string | null;
  payee?: Payee | null;
  description?: string | null;
  shipping?: Shipping | null;
  payments?: Payments | null;
  amount?: Amount | null;
}
export interface Payee {
  emailAddress: string;
  merchantId: string;
}
export interface Shipping {
  address: Address;
}
export interface Payments {
  authorizations?: Authorization[] | null;
  captures?: Capture[] | null;
}
export interface Authorization {
  id: string;
  status: string;
  amount: Amount;
  sellerProtection: SellerProtection;
  expirationTime: string;
  createTime: string;
  updateTime: string;
  links: Link[];
}
export interface Amount {
  currencyCode?: string;
  value: number | string;
}
export interface SellerProtection {
  status: string;
  disputeCategories: string[];
}
export interface Link {
  href: string;
  rel: string;
  method: string;
}
export interface Capture {
  id: string;
  status: string;
  amount: Amount;
  sellerProtection: SellerProtection;
  finalCapture: boolean;
  disbursementMode?: string | null;
  sellerReceivableBreakdown: SellerReceivableBreakdown;
  createTime: string;
  updateTime: string;
  links: Link[];
}
export interface SellerReceivableBreakdown {
  grossAmount: GrossAmount;
  paypalFee: PaypalFee;
  netAmount: NetAmount;
}
export interface GrossAmount {
  currencyCode: string;
  value: number | string;
}
export interface PaypalFee {
  currencyCode: string;
  value: number | string;
}
export interface NetAmount {
  currencyCode: string;
  value: number | string;
}
export interface Payer {
  name: Name;
  emailAddress: string;
  payerId: string;
}
