/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProductForUpdate {
  id: number;
  title: string;
  description?: string | null;
  price: number | string;
  mediumId: number;
  height: number;
  width: number;
  enabled: boolean;
  images?: string[] | null;
}
