/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProductOut {
  title: string;
  price: number | string;
  height: number;
  width: number;
  description: string | null;
  enabled: boolean;
  thumbnail: string;
  dateAdded: string;
  mediumId: number;
  storefrontId: number;
  id: number;
  images?: ProductImageOut[];
  medium?: MediumOut | null;
}
export interface ProductImageOut {
  publicId: string;
  position: number;
  width: number;
  height: number;
  productId: number;
  id: number;
}
export interface MediumOut {
  name: string;
  id: number;
}
