/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProductMetadata {
  priceRange: PriceRange;
  mediumCounts: MediumCount[];
  sizeRanges: SizeRanges;
}
export interface PriceRange {
  minimum: number | string;
  maximum: number | string;
}
export interface MediumCount {
  id: number;
  name: string;
  count: number;
}
export interface SizeRanges {
  widthMinimum: number;
  widthMaximum: number;
  heightMinimum: number;
  heightMaximum: number;
}
